/* ===========================================================================
   HANY APPAREL — store front-end
   ---------------------------------------------------------------------------
   Progressive enhancement throughout: every action here is also a real form
   POST that works with JavaScript disabled or broken. This file makes those
   actions feel instant, it is not what makes them work.

   TikTok events fired from the browser reuse the event_id generated by the
   server for the same action, so TikTok merges the pixel report and the Events
   API report instead of counting the conversion twice.
   =========================================================================== */

(function () {
    "use strict";

    /* ------------------------------ utilities ---------------------------- */

    var body = document.body;
    var CURRENCY = (body && body.dataset.currency) || "EGP";

    function $(selector, scope) {
        return (scope || document).querySelector(selector);
    }

    function $$(selector, scope) {
        return Array.prototype.slice.call((scope || document).querySelectorAll(selector));
    }

    function csrfToken() {
        var input = $('#csrf-holder input[name="csrfmiddlewaretoken"]');
        if (input) {
            return input.value;
        }
        // Fall back to the cookie if the holder form is missing.
        var match = document.cookie.match(/(^|;\s*)csrftoken=([^;]*)/);
        return match ? decodeURIComponent(match[2]) : "";
    }

    /** Format a decimal string the same way the `money` template filter does. */
    function money(value) {
        var amount = parseFloat(value);
        if (isNaN(amount)) {
            return value + " " + CURRENCY;
        }
        var text = Number.isInteger(amount)
            ? amount.toLocaleString("en-US")
            : amount.toLocaleString("en-US", {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2
              });
        return text + " " + CURRENCY;
    }

    /* -------------------------------- toasts ----------------------------- */

    var toastHost = $("#toast-host");

    function toast(message, kind) {
        if (!toastHost || !message) {
            return;
        }

        var el = document.createElement("div");
        el.className = "shop-toast" + (kind === "error" ? " shop-toast--error" : "");

        var icon = document.createElement("i");
        icon.className = kind === "error" ? "ri-error-warning-line" : "ri-check-line";
        icon.setAttribute("aria-hidden", "true");

        var text = document.createElement("span");
        text.textContent = message;

        el.appendChild(icon);
        el.appendChild(text);
        toastHost.appendChild(el);

        requestAnimationFrame(function () {
            el.classList.add("is-visible");
        });

        setTimeout(function () {
            el.classList.remove("is-visible");
            setTimeout(function () {
                if (el.parentNode) {
                    el.parentNode.removeChild(el);
                }
            }, 320);
        }, 3200);
    }

    /* ------------------------------ bag badge ---------------------------- */

    function setBagCount(count) {
        var badge = $("#bag-count");
        if (!badge) {
            return;
        }

        badge.textContent = count;
        badge.dataset.count = count;
        badge.classList.toggle("is-empty", !count);

        badge.classList.add("is-bumped");
        setTimeout(function () {
            badge.classList.remove("is-bumped");
        }, 320);
    }

    /* ------------------------------ requests ----------------------------- */

    /**
     * POST form data to a store endpoint and return the parsed JSON.
     * Rejects with a message suitable for showing to the customer.
     */
    function post(url, data) {
        var form = new FormData();
        Object.keys(data).forEach(function (key) {
            form.append(key, data[key]);
        });

        return fetch(url, {
            method: "POST",
            body: form,
            credentials: "same-origin",
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": csrfToken(),
                Accept: "application/json"
            }
        })
            .then(function (response) {
                return response.json().then(function (payload) {
                    return { ok: response.ok, payload: payload };
                });
            })
            .then(function (result) {
                var payload = result.payload || {};
                if (!payload.ok) {
                    throw new Error(payload.message || "Something went wrong.");
                }
                return payload;
            });
    }

    /* --------------------------- TikTok helpers -------------------------- */

    function track(event, properties, eventId) {
        if (typeof window.ttq === "undefined") {
            return;
        }
        try {
            if (eventId) {
                window.ttq.track(event, properties || {}, { event_id: eventId });
            } else {
                window.ttq.track(event, properties || {});
            }
        } catch (err) {
            /* Analytics must never break the shop. */
        }
    }

    // ViewContent / InitiateCheckout / CompletePayment are declared by the
    // template as data attributes, so the ids match the server-side events.
    $$("[data-tt-event]").forEach(function (node) {
        var properties = {};
        if (node.dataset.ttProperties) {
            try {
                properties = JSON.parse(node.dataset.ttProperties);
            } catch (err) {
                properties = {};
            }
        }
        track(node.dataset.ttEvent, properties, node.dataset.ttEventId);
    });

    /* -------------------------- card image turn -------------------------- */

    $$(".shop-card__turn").forEach(function (button) {
        button.addEventListener("click", function (event) {
            event.preventDefault();
            var card = button.closest(".shop-card");
            if (card) {
                card.classList.toggle("is-turned");
            }
        });
    });

    /* ---------------------------- add to bag ----------------------------- */

    function addToBag(trigger) {
        var form = trigger.closest("form");
        if (!form) {
            return;
        }

        var slug = form.dataset.slug || "";
        var sizeInput = form.querySelector('input[name="size"]:checked') ||
            form.querySelector('input[name="size"]') ||
            form.querySelector('select[name="size"]');
        var size = sizeInput ? sizeInput.value : "";
        var qtyInput = form.querySelector('input[name="quantity"]');
        var quantity = qtyInput ? qtyInput.value : 1;
        var errorBox = form.querySelector(".shop-inline-error");

        if (!size) {
            if (errorBox) {
                errorBox.textContent = "Choose a size first.";
                errorBox.classList.add("is-visible");
            }
            toast("Choose a size first.", "error");
            return;
        }

        if (errorBox) {
            errorBox.classList.remove("is-visible");
        }

        var originalLabel = trigger.innerHTML;
        trigger.classList.add("is-busy");
        trigger.disabled = true;

        post(form.action, { slug: slug, size: size, quantity: quantity })
            .then(function (payload) {
                setBagCount(payload.cart.count);
                toast(payload.message);

                track(
                    "AddToCart",
                    {
                        currency: CURRENCY,
                        value: parseFloat(form.dataset.price || "0") * parseInt(quantity, 10),
                        content_type: "product",
                        contents: [
                            {
                                content_id: slug,
                                content_type: "product",
                                content_name: form.dataset.name || slug,
                                quantity: parseInt(quantity, 10),
                                price: parseFloat(form.dataset.price || "0")
                            }
                        ]
                    },
                    payload.event_id
                );

                trigger.innerHTML =
                    '<i class="ri-check-line" aria-hidden="true"></i> Added';
                setTimeout(function () {
                    trigger.innerHTML = originalLabel;
                }, 1600);
            })
            .catch(function (err) {
                toast(err.message, "error");
                if (errorBox) {
                    errorBox.textContent = err.message;
                    errorBox.classList.add("is-visible");
                }
            })
            .finally(function () {
                trigger.classList.remove("is-busy");
                trigger.disabled = false;
            });
    }

    $$("[data-add-to-bag]").forEach(function (trigger) {
        trigger.addEventListener("click", function (event) {
            // Only intercept when fetch is usable; otherwise let the form post.
            if (typeof window.fetch !== "function") {
                return;
            }
            event.preventDefault();
            addToBag(trigger);
        });
    });

    /* ------------------------- quantity steppers ------------------------- */

    $$("[data-stepper]").forEach(function (stepper) {
        var input = stepper.querySelector("input");
        var minus = stepper.querySelector('[data-step="down"]');
        var plus = stepper.querySelector('[data-step="up"]');

        if (!input) {
            return;
        }

        function clamp(value) {
            var min = parseInt(input.min || "1", 10);
            var max = parseInt(input.max || "99", 10);
            if (isNaN(value) || value < min) {
                return min;
            }
            return value > max ? max : value;
        }

        function sync() {
            var value = clamp(parseInt(input.value, 10));
            input.value = value;
            if (minus) {
                minus.disabled = value <= parseInt(input.min || "1", 10);
            }
            if (plus) {
                plus.disabled = value >= parseInt(input.max || "99", 10);
            }
        }

        function nudge(delta) {
            input.value = clamp(parseInt(input.value, 10) + delta);
            sync();
            input.dispatchEvent(new Event("change", { bubbles: true }));
        }

        if (minus) {
            minus.addEventListener("click", function (event) {
                event.preventDefault();
                nudge(-1);
            });
        }
        if (plus) {
            plus.addEventListener("click", function (event) {
                event.preventDefault();
                nudge(1);
            });
        }
        input.addEventListener("change", sync);
        sync();
    });

    /* ------------------------------- gallery ----------------------------- */

    var gallery = $("[data-gallery]");
    if (gallery) {
        var slides = $$("[data-gallery-slide]", gallery);
        var thumbs = $$("[data-gallery-thumb]", gallery);

        function show(index) {
            slides.forEach(function (slide, i) {
                slide.classList.toggle("is-active", i === index);
            });
            thumbs.forEach(function (thumb, i) {
                thumb.classList.toggle("is-active", i === index);
                thumb.setAttribute("aria-selected", i === index ? "true" : "false");
            });
        }

        thumbs.forEach(function (thumb, index) {
            thumb.addEventListener("click", function (event) {
                event.preventDefault();
                show(index);
            });
        });
    }

    /* ------------------------------ cart page ---------------------------- */

    var cartRoot = $("[data-cart-root]");

    if (cartRoot) {
        var updateUrl = cartRoot.dataset.updateUrl;
        var removeUrl = cartRoot.dataset.removeUrl;
        var threshold = parseFloat(cartRoot.dataset.freeShippingThreshold || "0");

        function refresh(cart) {
            setBagCount(cart.count);

            if (!cart.lines.length) {
                // Nothing left: reload so the empty-bag state renders.
                window.location.reload();
                return;
            }

            var present = {};
            cart.lines.forEach(function (line) {
                present[line.key] = true;

                var row = cartRoot.querySelector('[data-line-key="' + line.key + '"]');
                if (!row) {
                    return;
                }

                var input = row.querySelector('input[name="quantity"]');
                if (input) {
                    input.value = line.quantity;
                    input.max = line.max_quantity;
                }

                var total = row.querySelector("[data-line-total]");
                if (total) {
                    total.textContent = money(line.line_total);
                }
            });

            // Drop rows the server no longer knows about.
            $$("[data-line-key]", cartRoot).forEach(function (row) {
                if (!present[row.dataset.lineKey]) {
                    row.remove();
                }
            });

            var subtotalEl = $("[data-subtotal]", cartRoot);
            if (subtotalEl) {
                subtotalEl.textContent = money(cart.subtotal);
            }

            var shippingEl = $("[data-shipping]", cartRoot);
            if (shippingEl) {
                var shipping = parseFloat(cart.shipping);
                shippingEl.textContent = shipping > 0 ? money(cart.shipping) : "Free";
            }

            var totalEl = $("[data-total]", cartRoot);
            if (totalEl) {
                totalEl.textContent = money(cart.total);
            }

            // Free-shipping progress reflects the real remaining amount.
            var progress = $("[data-progress]", cartRoot);
            if (progress && threshold > 0) {
                var subtotal = parseFloat(cart.subtotal);
                var remaining = Math.max(threshold - subtotal, 0);
                var bar = $("[data-progress-bar]", progress);
                var label = $("[data-progress-label]", progress);

                if (bar) {
                    bar.style.width = Math.min((subtotal / threshold) * 100, 100) + "%";
                }
                if (label) {
                    label.innerHTML = remaining > 0
                        ? "Add <strong>" + money(remaining) + "</strong> more for free delivery."
                        : "<strong>Free delivery unlocked.</strong>";
                }
            }
        }

        // Quantity changes are debounced: holding the + button should send one
        // request, not one per click.
        var timers = {};

        cartRoot.addEventListener("change", function (event) {
            var input = event.target;
            if (!input.matches('input[name="quantity"]')) {
                return;
            }

            var row = input.closest("[data-line-key]");
            if (!row) {
                return;
            }
            var key = row.dataset.lineKey;

            clearTimeout(timers[key]);
            timers[key] = setTimeout(function () {
                post(updateUrl, { key: key, quantity: input.value })
                    .then(function (payload) {
                        refresh(payload.cart);
                    })
                    .catch(function (err) {
                        toast(err.message, "error");
                        window.location.reload();
                    });
            }, 350);
        });

        cartRoot.addEventListener("click", function (event) {
            var button = event.target.closest("[data-remove]");
            if (!button || typeof window.fetch !== "function") {
                return;
            }
            event.preventDefault();

            var row = button.closest("[data-line-key]");
            if (!row) {
                return;
            }

            button.disabled = true;
            post(removeUrl, { key: row.dataset.lineKey })
                .then(function (payload) {
                    row.remove();
                    refresh(payload.cart);
                    toast(payload.message);
                })
                .catch(function (err) {
                    button.disabled = false;
                    toast(err.message, "error");
                });
        });
    }

    /* ---------------------- checkout submit guard ------------------------ */

    // Double-clicking "Place order" must not create two orders or two invoices.
    $$("[data-guard-submit]").forEach(function (form) {
        form.addEventListener("submit", function () {
            var button = form.querySelector('[type="submit"]');
            if (!button) {
                return;
            }
            if (form.dataset.submitted === "1") {
                return;
            }
            form.dataset.submitted = "1";
            button.classList.add("is-busy");
            button.disabled = true;
            button.innerHTML =
                '<i class="ri-loader-4-line" aria-hidden="true"></i> Placing your order…';

            // Re-enable if the browser restores the page from history, so a
            // customer who hits Back is not left with a dead button.
            window.addEventListener("pageshow", function () {
                form.dataset.submitted = "";
                button.classList.remove("is-busy");
                button.disabled = false;
            });
        });
    });

    /* -------------------- payment method interaction --------------------- */

    var payRadios = $$('input[name="payment"]');
    var emailGroup = $("[data-email-group]");

    function syncEmailRequirement() {
        if (!emailGroup) {
            return;
        }
        var selected = payRadios.filter(function (radio) {
            return radio.checked;
        })[0];
        var online = selected && selected.value === "online";
        var input = emailGroup.querySelector("input");
        var flag = emailGroup.querySelector("[data-email-required]");

        if (input) {
            input.required = !!online;
        }
        if (flag) {
            flag.hidden = !online;
        }
    }

    payRadios.forEach(function (radio) {
        radio.addEventListener("change", syncEmailRequirement);
    });
    syncEmailRequirement();
})();
